version: 2
sources:
    - name: datafeed_shared_schema
      database: "{{('dbt_lab')}}"
      schema: stage_layer
      tables:
        - name: stg_customerdata
        - name: stg_payments
        - name: stg_orders
        - name: STG_ITEMS_DATA
        - name: STG_PRODUCT_DATA
        - name: STG_SUPPLIES_DATA
